# Generated by Django 3.1.4 on 2020-12-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201223_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='first_name',
            field=models.CharField(help_text='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='last_name',
            field=models.CharField(help_text='Surname', max_length=50),
        ),
    ]
