# Generated by Django 3.1.4 on 2020-12-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_dragons_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='password',
        ),
    ]
