# Generated by Django 3.1.4 on 2020-12-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_buyers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyers',
            name='published',
        ),
        migrations.AddField(
            model_name='orderdragon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
