# Generated by Django 3.1.4 on 2020-12-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20201228_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdragon',
            name='email',
        ),
    ]
