# Generated by Django 3.1.4 on 2020-12-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_orderdragon_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainoder',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='orderdragon',
            name='dragon',
        ),
        migrations.RemoveField(
            model_name='orderdragon',
            name='mainOder',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='dragon',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='mainOder',
        ),
        migrations.AddField(
            model_name='buyers',
            name='dragon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.dragons'),
        ),
        migrations.DeleteModel(
            name='DFood',
        ),
        migrations.DeleteModel(
            name='MainOder',
        ),
        migrations.DeleteModel(
            name='OrderDragon',
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
    ]
