# Generated by Django 3.1.4 on 2020-12-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20201228_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='cellphon',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11),
        ),
    ]
