# Generated by Django 3.1.4 on 2020-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20201228_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='cellphon',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='first_name',
            field=models.CharField(blank=True, help_text='Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='last_name',
            field=models.CharField(blank=True, help_text='Surname', max_length=50, null=True),
        ),
    ]
