# Generated by Django 3.1.4 on 2020-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20201228_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='cellphon',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
