# Generated by Django 3.1.4 on 2020-12-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20201228_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='dragon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
