# Generated by Django 3.1.4 on 2020-12-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20201228_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyers',
            old_name='cellphon',
            new_name='cellphone',
        ),
    ]
